#!/bin/bash
echo $$ > ../db/pidfile
multicore_done=0
while read line
do
if [[ "$line" == "multicore" ]]
then
  touch /home/comp/COMPUT/work/crit/multicore
	multicore_done=1
echo "rm -f /home/comp/COMPUT/work/crit/multicore" >> ./stop_computations
break
fi
done<./job_config.txt
echo "exit 0" >> ./stop_computations
./computation.sh
if [[ "$multicore_done" -eq "1" ]]
then
	rm -f /home/comp/COMPUT/work/crit/multicore
fi
exit 0
